# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  encoding: SQL_ASCII
  database: store_development
  pool: 5
  username: postgres
  password: 6oebR!eP

test:
  adapter: postgresql
  encoding: SQL_ASCII
  database: store_test
  pool: 5
  username: postgres
  password: 6oebR!eP
