# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bb0eb9efba09ffdceef753ea2d11ccd81b8368a2248bc5df4d4cf04ca1f324c078a29cd411a634a9e2ea6252dffa0b33d8df3579fadb1a151fa30cab38d87379

test:
  secret_key_base: 3eae0dc792ac2d3186e264cc27546bc50597e51267b818e41f7f5a2a93848ced1d8d5df6cb00c77043d6dd2335dfba59c4c97166c4c09fb93759dd8a17dbd724

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
